resources:
  - type: storage.v1.bucket
    name: sls-serverless-dev-1630407891849
    properties:
      location: asia-northeast3
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: serverless-dev-test
    properties:
      parent: projects/makasete/locations/asia-northeast3
      availableMemoryMb: 512
      runtime: nodejs14
      timeout: 60s
      entryPoint: test
      function: serverless-dev-test
      sourceArchiveUrl: >-
        gs://sls-serverless-dev-1630407891849/serverless/serverless/dev/1631547537170-2021-09-13T15:38:57.170Z/serverless.zip
      environmentVariables:
        HOST: https://makasete.vercel.app/
      labels: {}
      httpsTrigger:
        url: test
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: serverless-dev-ocr
    properties:
      parent: projects/makasete/locations/asia-northeast3
      availableMemoryMb: 512
      runtime: nodejs14
      timeout: 60s
      entryPoint: ocr
      function: serverless-dev-ocr
      sourceArchiveUrl: >-
        gs://sls-serverless-dev-1630407891849/serverless/serverless/dev/1631547537170-2021-09-13T15:38:57.170Z/serverless.zip
      environmentVariables:
        HOST: https://makasete.vercel.app/
      labels: {}
      httpsTrigger:
        url: ocr
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: serverless-dev-dict
    properties:
      parent: projects/makasete/locations/asia-northeast3
      availableMemoryMb: 512
      runtime: nodejs14
      timeout: 60s
      entryPoint: dict
      function: serverless-dev-dict
      sourceArchiveUrl: >-
        gs://sls-serverless-dev-1630407891849/serverless/serverless/dev/1631547537170-2021-09-13T15:38:57.170Z/serverless.zip
      environmentVariables:
        HOST: https://makasete.vercel.app/
      labels: {}
      httpsTrigger:
        url: dict
